name: Generate Javadoc and Deploy to gh-pages

on:
  push:
    branches: [main]

jobs:
  generate-and-deploy-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build and generate aggregate Javadoc
        run: mvn clean javadoc:aggregate

      - name: List javadoc generated files 
        run: ls -lR target

      - name: Create docs branch and copy Javadoc
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git switch --orphan docs
          cp -r target/reports/apidocs /tmp/javadoc-copy
          cp -r .git /tmp
          rm -rf -- * .[^.]* || true
          mkdir -p docs
          cp -r /tmp/javadoc-copy/* docs/
          cp -r /tmp/.git ./
          git add docs
          git commit -m "Generate Javadoc documentation"
      
      - name: Push doc branch
        run: |
          git push -fu origin docs

      - name: Deploy docs to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: docs
